services:
  - type: web
    name: whatsapp-web
    env: container
    plan: free
    repo: https://github.com/alnomaanbd71/whatsapp-checker
    branch: main
    buildCommand: docker build -t whatsapp-web .
    startCommand: whatsapp-web   # run the image by its name
